[package]
name = "libnewsboat-ffi"
version = "2.19.1"
authors = ["Alexander Batischev <eual.jp@gmail.com>"]

[dependencies]
libnewsboat = { path="../libnewsboat" }
libc = "0.2"

[lib]
name = "newsboat"
crate-type = ["staticlib"]
